# etl.py
import pandas as pd
import sqlite3

# Load the raw CSV generated by consumer
df = pd.read_csv("../data/raw_games.csv")

# --- Data Cleaning ---
# Fill missing values
df['price'] = df['price'].fillna(0)
df['release_date'] = df['release_date'].fillna("Unknown")
df['user_score'] = df['user_score'].fillna(0)
df['metacritic_score'] = df['metacritic_score'].fillna(0)

# Convert release_date to datetime
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

# Optional: Convert price to float
df['price'] = df['price'].astype(float)

# Drop duplicate games
df = df.drop_duplicates(subset=['name'])

# --- Store in SQLite ---
conn = sqlite3.connect("steam_games.db")
df.to_sql("games", conn, if_exists="replace", index=False)
conn.close()

print("ETL finished. Data stored in steam_games.db (table: games).")
